### ISSUE TITLE
Audio record only lasts 1 second

### ISSUE THREAD

**Issue by goergen95** [Nature40/pysensorproxy#3]
https://github.com/Nature40/pysensorproxy/blob/b5444308b89503c9719a57a561fa435af23089c7/sensorproxy/sensors/audio.py#L13

In the default setting the audio recording currently only lasts for one second. Can you please create a config file to enable users to specifiy length of audio recording?

**Comment by jonashoechst** [comment]
The requested config file can be found [here](https://github.com/Nature40/pysensorproxy/blob/master/examples/meterings.yml).

```yml
morning:              # name of the measuring cycle
  sensors:              # dict of the sensors to be measured
    cam:                  # reference to `cam`, configured in the static config (yml)
      res_X: 3280           # image resolution, set according to https://www.raspberrypi.org/documentation/raspbian/applications/camera.md
      res_Y: 2464
      adjust_time_s: 2      # time to adjust to brightness
    mic:
      duration_s: 1         # duration of the audio file to be recorded
```
